source "https://rubygems.org"

gem 'sinatra'
gem 'nokogiri'
gem 'rspec'
gem 'rack-test'
gem 'capybara', '0.3.9'
gem "sinatra-activerecord"
gem "sqlite3"
gem "rake"


  gem 'rspec'
  gem "fabrication"
  gem 'factory_girl', '~> 2.0.0'
  gem "database_cleaner"


group :development do
  gem "sinatra-reloader"
end