require "sinatra/activerecord/rake"

namespace :db do
  task :load_config do
    require "./boot"
  end
end

require './models.rb'
desc 'Create some testing data'

  task :fake_database do
    10.times do
      Fabricate(:author)
    end
  end